foreground            #dee3e6
background            #0f1416
selection_foreground  #cfe6f1
selection_background  #344a52
url_color             #88d1ec
cursor                #88d1ec
cursor_text_color     #003544

active_tab_foreground   #003544
active_tab_background   #88d1ec
inactive_tab_foreground #bfc8cc
inactive_tab_background #40484c

# Black
color0 #0f1416
color8 #40484c

# Red
color1 #ffb4ab
color9 #ffb4ab

# Green
color2 #c3c3eb
color10 #c3c3eb

# Yellow
color3 #b3cad4
color11 #b3cad4

# Blue
color4 #88d1ec
color12 #88d1ec

# Magenta
color5 #004d61
color13 #004d61

# Cyan
color6 #434465
color14 #434465

# White
color7 #dee3e6
color15 #bfc8cc
