foreground            #dee4e0
background            #0e1513
selection_foreground  #cde8df
selection_background  #334b45
url_color             #85d6c1
cursor                #85d6c1
cursor_text_color     #00382e

active_tab_foreground   #00382e
active_tab_background   #85d6c1
inactive_tab_foreground #bfc9c4
inactive_tab_background #3f4946

# Black
color0 #0e1513
color8 #3f4946

# Red
color1 #ffb4ab
color9 #ffb4ab

# Green
color2 #aacbe4
color10 #aacbe4

# Yellow
color3 #b1ccc4
color11 #b1ccc4

# Blue
color4 #85d6c1
color12 #85d6c1

# Magenta
color5 #005144
color13 #005144

# Cyan
color6 #2a4a5f
color14 #2a4a5f

# White
color7 #dee4e0
color15 #bfc9c4
