foreground            #dfe3e7
background            #0f1417
selection_foreground  #d1e5f3
selection_background  #364954
url_color             #8ecff2
cursor                #8ecff2
cursor_text_color     #003548

active_tab_foreground   #003548
active_tab_background   #8ecff2
inactive_tab_foreground #c0c7cd
inactive_tab_background #40484d

# Black
color0 #0f1417
color8 #40484d

# Red
color1 #ffb4ab
color9 #ffb4ab

# Green
color2 #c9c1ea
color10 #c9c1ea

# Yellow
color3 #b5c9d7
color11 #b5c9d7

# Blue
color4 #8ecff2
color12 #8ecff2

# Magenta
color5 #004d67
color13 #004d67

# Cyan
color6 #484364
color14 #484364

# White
color7 #dfe3e7
color15 #c0c7cd
