-- ─────────────────────────────────────────────
--   Hyprland Colors — Lua (generated by Matugen)
--   Mirrors colors.conf · do not edit manually
--   Source template: matugen/templates/hyprland.lua
-- ─────────────────────────────────────────────
-- Provides active_border / inactive_border / background as globals
-- and as a return table for `require("colors")`.

active_border = "85d6c1"
inactive_border = "3f4946"
background = "0e1513"

return {
    active_border = active_border,
    inactive_border = inactive_border,
    background = background,
}
